version: '3.4'

services:
  php:
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/php:/usr/local/etc/php:ro,cached
      - ./:/app
      - ./var/log/php:/var/log:rw
    expose:
      - 9000



